// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYVurPQImVWmZfpCTNRWD9eNrqH8U7lc',
    appId: '1:435305050222:web:ae1685a027652c6d7d767f',
    messagingSenderId: '435305050222',
    projectId: 'dz-room',
    authDomain: 'dz-room.firebaseapp.com',
    storageBucket: 'dz-room.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qE6a3aGNtSeTque_UzpkzoLX-eLX2ws',
    appId: '1:435305050222:android:8d411d6c9ddc12b27d767f',
    messagingSenderId: '435305050222',
    projectId: 'dz-room',
    storageBucket: 'dz-room.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGt8nSAuYYXHZQOJWOtMyw8qFhrr8r28',
    appId: '1:435305050222:ios:1b9ddda12edb33277d767f',
    messagingSenderId: '435305050222',
    projectId: 'dz-room',
    storageBucket: 'dz-room.firebasestorage.app',
    iosBundleId: 'com.example.roomdzFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGt8nSAuYYXHZQOJWOtMyw8qFhrr8r28',
    appId: '1:435305050222:ios:1b9ddda12edb33277d767f',
    messagingSenderId: '435305050222',
    projectId: 'dz-room',
    storageBucket: 'dz-room.firebasestorage.app',
    iosBundleId: 'com.example.roomdzFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEYVurPQImVWmZfpCTNRWD9eNrqH8U7lc',
    appId: '1:435305050222:web:e7254d03b79055187d767f',
    messagingSenderId: '435305050222',
    projectId: 'dz-room',
    authDomain: 'dz-room.firebaseapp.com',
    storageBucket: 'dz-room.firebasestorage.app',
  );
}
